databases:
  - name: cafe
    databaseName: cafee
    user: cafe
    plan: free

services:
  - type: web
    name: caffe
    env: ruby
    plan: free
    buildCommand: "./bin/render_build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cafe
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false